# Generated by Django 5.2.7 on 2025-10-04 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approved',
        ),
        migrations.AddField(
            model_name='approval',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='REJECTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='approval',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='expenses.expense'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(fields=('expense', 'manager'), name='unique_manager_review'),
        ),
    ]
