# Generated by Django 5.2.7 on 2025-10-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_remove_approval_approved_approval_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=10),
        ),
    ]
