# Generated by Django 5.2.7 on 2025-10-04 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
